import { prisma } from '../db';
import { generateMermaidGraph } from './mermaid';

export async function generateArchitectureDocs(projectName: string, branch: string = 'main'): Promise<string> {

    // 1. Fetch Project
    const project = await prisma.project.findUnique({
        where: { name: projectName }
    });

    if (!project) {
        throw new Error(`Project ${projectName} not found.`);
    }

    // 2. Fetch all data for the branch concurrently
    const [tasks, memories, decisions] = await Promise.all([
        prisma.task.findMany({
            where: { projectId: project.id, gitBranch: branch },
            include: { decisions: true },
            orderBy: { createdAt: 'asc' }
        }),
        prisma.memory.findMany({
            where: { projectId: project.id, gitBranch: branch },
            orderBy: { createdAt: 'asc' }
        }),
        prisma.decision.findMany({
            where: { task: { projectId: project.id }, gitBranch: branch },
            orderBy: { createdAt: 'asc' }
        })
    ]);

    // 3. Assemble Markdown
    let md = `# ARCHITECTURE.md\n\n`;
    md += `> **Project**: ${project.name} | **Branch**: ${branch}\n`;
    md += `> *Autogenerated by \`aigit docs\` carefully assembling Semantic Memory*\n\n`;

    // ── Semantic DAG ──────────────────────────────────────────────
    md += `## Semantic Causal Graph\n\n`;
    md += `This diagram illustrates the causal relationships between Memories, Tasks, and Decisions, grouped by file location.\n\n`;
    md += generateMermaidGraph(tasks, memories, decisions);
    md += `\n\n`;

    // ── Core Memories ─────────────────────────────────────────────
    md += `## Core Principles & Memories\n\n`;
    const coreMemories = memories.filter(m => !m.filePath);
    if (coreMemories.length === 0) {
        md += `*No core memories recorded yet.*\n\n`;
    } else {
        coreMemories.forEach(m => {
            md += `- **[${m.type}]**: ${m.content} *(Added: ${m.createdAt.toISOString().split('T')[0]})*\n`;
        });
        md += `\n`;
    }

    // ── File-Based Context ────────────────────────────────────────
    md += `## Implementation Details (By File)\n\n`;

    // Pre-group decisions by filePath for faster lookups
    const decisionsByFile = new Map<string, typeof decisions>();
    for (const d of decisions) {
        if (!d.filePath) continue;
        let group = decisionsByFile.get(d.filePath);
        if (!group) {
            group = [];
            decisionsByFile.set(d.filePath, group);
        }
        group.push(d);
    }

    // Pre-group memories by filePath
    const memoriesByFile = new Map<string, typeof memories>();
    for (const mem of memories) {
        if (!mem.filePath) continue;
        let group = memoriesByFile.get(mem.filePath);
        if (!group) {
            group = [];
            memoriesByFile.set(mem.filePath, group);
        }
        group.push(mem);
    }

    const files = new Set<string>();
    for (const f of memoriesByFile.keys()) files.add(f);
    for (const f of decisionsByFile.keys()) files.add(f);

    if (files.size === 0) {
        md += `*No file-specific context recorded yet.*\n\n`;
    } else {
        const sortedFiles = Array.from(files).sort();
        for (const file of sortedFiles) {
            md += `### \`${file}\`\n\n`;

            const fileMemories = memoriesByFile.get(file) || [];
            // Filter out default fallback git hooks so we only show dense semantic memories per file
            const semanticFileMemories = fileMemories.filter(m => !m.content.startsWith('Automatic Git Commit Context'));
            
            if (semanticFileMemories.length > 0) {
                md += `**Memories:**\n`;
                semanticFileMemories.forEach(m => {
                    const symbol = m.symbolName ? ` \`@${m.symbolName}\`` : '';
                    let cleanContent = m.content;
                    if (cleanContent.includes('Files Changed:') && cleanContent.includes('Statistics:')) {
                        cleanContent = cleanContent.split('\n')[0].trim() + ' *(Diff omitted for brevity)*';
                    } else if (cleanContent.length > 300) {
                        cleanContent = cleanContent.substring(0, 300) + '...';
                    }
                    md += `- [${m.type}]${symbol}: ${cleanContent}\n`;
                });
                md += `\n`;
            }

            const fileDecisions = decisionsByFile.get(file) || [];
            if (fileDecisions.length > 0) {
                md += `**Decisions:**\n`;
                fileDecisions.forEach(d => {
                    const symbol = d.symbolName ? ` \`@${d.symbolName}\`` : '';
                    md += `- ${symbol}: Choose **${d.chosen}** over (${d.rejected.join(', ')}).\n`;
                    md += `  > *Reasoning: ${d.reasoning}*\n`;
                });
                md += `\n`;
            }
        }
    }

    // ── Tasks ─────────────────────────────────────────────────────
    md += `## Task History\n\n`;
    if (tasks.length === 0) {
        md += `*No tasks recorded yet.*\n\n`;
    } else {
        tasks.forEach(task => {
            const statusIcon =
                task.status === 'DONE' ? '✅' :
                task.status === 'BLOCKED' ? '⚠️' :
                task.status === 'CANCELLED' ? '❌' :
                task.status === 'PLANNING' ? '📋' :
                task.status === 'REVIEW' ? '🔍' :
                '🔄'; // IN_PROGRESS
            md += `### ${statusIcon} ${task.title} (\`${task.slug}\`)\n`;
            md += `- **Status**: ${task.status}\n`;
            md += `- **Branch**: ${task.gitBranch}\n`;
            md += `- **Created**: ${task.createdAt.toISOString().split('T')[0]}\n`;
            md += `- **Plan**: \`.aigit/tasks/${task.slug}.md\`\n`;
            if (task.decisions.length > 0) {
                md += `- **Outcomes**:\n`;
                task.decisions.forEach(d => {
                    const loc = d.filePath ? ` (in \`${d.filePath}\`)` : '';
                    md += `  - Decided on **${d.chosen}**${loc}.\n`;
                });
            }
            md += `\n`;
        });
    }

    return md;
}
